# RedHat related OSs
- name: Yum install ganglia-gmond
  action: yum pkg=ganglia-gmond state=present
  when: "ansible_os_family == 'RedHat'"

# Debian related OSs
- name: Apt install ganglia-monitor
  action: apt pkg=ganglia-monitor state=present
  when: "ansible_os_family == 'Debian'"

- name: configure gmond
  action: template src=gmond.conf dest=/etc/ganglia/gmond.conf owner=root group=root
  notify:
      - restart gmond
      - restart ganglia-monitor

- name: start gmond
  action: service name=gmond state=started
  when: "ansible_os_family == 'RedHat'"

- name: initially restart gmond
  action: service name=gmond state=restarted
  when: "ansible_os_family == 'RedHat'"

- name: itially restart ganglia-monitor
  action: service name=ganglia-monitor state=restarted pattern=/usr/sbin/gmond
  when: "ansible_os_family == 'Debian'"
